CATEGORIES_QUERY = """
SELECT
    c.uid,
    p.NAME AS CATEGORY,
    c.NAME AS SUBCATEGORY
FROM ZCATEGORY c
LEFT JOIN ZCATEGORY p
    ON c.pUid = p.uid
WHERE c.TYPE IN (0, 1)
ORDER BY CATEGORY, SUBCATEGORY;
"""